create table if not exists public.user_password_credentials (
  user_id uuid primary key references public.users(id) on delete cascade,
  password_hash text not null,
  hash_algorithm text not null default 'bcrypt'
    check (hash_algorithm in ('bcrypt', 'argon2id')),
  password_updated_at timestamptz not null default now(),
  must_reset_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_password_credentials_hash_format
    check (
      (hash_algorithm = 'bcrypt' and password_hash ~ '^\$2[aby]\$[0-9]{2}\$')
      or
      (hash_algorithm = 'argon2id' and password_hash ~ '^\$argon2id\$')
    )
);

alter table public.user_password_credentials
  drop constraint if exists user_password_credentials_hash_format;

alter table public.user_password_credentials
  add constraint user_password_credentials_hash_format
    check (
      (hash_algorithm = 'bcrypt' and password_hash ~ '^\$2[aby]\$[0-9]{2}\$')
      or
      (hash_algorithm = 'argon2id' and password_hash ~ '^\$argon2id\$')
    );

alter table public.user_password_credentials enable row level security;

create index if not exists user_password_credentials_updated_at_idx
  on public.user_password_credentials(password_updated_at desc);

comment on table public.user_password_credentials is
  'Stores password hashes only. Never store raw passwords in this table.';

comment on column public.user_password_credentials.password_hash is
  'A bcrypt or argon2id hash generated by trusted server-side code.';
